packages: []
allowBuilds:
  esbuild: true
  embedded-postgres: true
  ffmpeg-static: true
  "@embedded-postgres/windows-x64": true
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/linux-arm64": true
