CREATE TABLE schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE bootstrap (singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), completed boolean NOT NULL DEFAULT false);
INSERT INTO bootstrap DEFAULT VALUES;
CREATE TABLE users (id uuid PRIMARY KEY, login text UNIQUE NOT NULL, display_name text NOT NULL, password_hash text, admin boolean NOT NULL DEFAULT false, enabled boolean NOT NULL DEFAULT true, mfa_secret text, mfa_counter bigint NOT NULL DEFAULT -1, recovery_hashes jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invitations (token_hash text PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE challenges (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), secret text, expires_at timestamptz NOT NULL, attempts integer NOT NULL DEFAULT 0);
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf_token text NOT NULL, mfa_verified boolean NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE events (id uuid PRIMARY KEY, name text NOT NULL, date text, location text NOT NULL DEFAULT '', modules jsonb NOT NULL, revision integer NOT NULL DEFAULT 1, created_by uuid REFERENCES users(id), updated_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE grants (event_id uuid REFERENCES events(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), role text NOT NULL CHECK(role IN ('leitung','live','technik','mitglied')), PRIMARY KEY(event_id,user_id,role));
CREATE TABLE teams (id uuid PRIMARY KEY, name text NOT NULL, created_by uuid REFERENCES users(id));
CREATE TABLE team_members (team_id uuid REFERENCES teams(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id), PRIMARY KEY(team_id,user_id));
CREATE TABLE event_teams (event_id uuid REFERENCES events(id) ON DELETE CASCADE, team_id uuid REFERENCES teams(id), PRIMARY KEY(event_id,team_id));
CREATE TABLE shows (id uuid PRIMARY KEY, event_id uuid REFERENCES events(id), name text NOT NULL, description text NOT NULL DEFAULT '', cues jsonb NOT NULL DEFAULT '[]', revision integer NOT NULL DEFAULT 1, source_show_id uuid REFERENCES shows(id), source_revision integer, created_by uuid NOT NULL REFERENCES users(id), updated_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE show_teams (show_id uuid REFERENCES shows(id) ON DELETE CASCADE, team_id uuid REFERENCES teams(id), PRIMARY KEY(show_id,team_id));
CREATE TABLE media (id uuid PRIMARY KEY, event_id uuid REFERENCES events(id), show_id uuid REFERENCES shows(id), created_by uuid NOT NULL REFERENCES users(id), name text NOT NULL, blob_key text UNIQUE NOT NULL, size_bytes bigint NOT NULL, sha256 text NOT NULL, mime text NOT NULL, status text NOT NULL CHECK(status IN ('processing','ready','failed')), analysis jsonb NOT NULL DEFAULT '{}', error text, lease_until timestamptz, attempts integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), CHECK((event_id IS NULL) <> (show_id IS NULL)));
CREATE TABLE show_media (show_id uuid REFERENCES shows(id) ON DELETE CASCADE, media_id uuid REFERENCES media(id), PRIMARY KEY(show_id,media_id));
CREATE TABLE revisions (entity_type text NOT NULL, entity_id uuid NOT NULL, revision integer NOT NULL, payload jsonb NOT NULL, actor_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(entity_type,entity_id,revision));
CREATE TABLE packages (id uuid PRIMARY KEY, event_id uuid NOT NULL REFERENCES events(id), manifest jsonb NOT NULL, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mail_jobs (id uuid PRIMARY KEY, business_key text UNIQUE NOT NULL, recipient text NOT NULL, subject text NOT NULL, body text NOT NULL, status text NOT NULL CHECK(status IN ('queued','sending','simulated','accepted_by_smtp','failed','unknown')), attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, provider_message_id text, last_error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE INDEX grants_user ON grants(user_id);
CREATE INDEX media_work ON media(status,lease_until);
INSERT INTO schema_migrations(version) VALUES(1);
